version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: flowsql-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "flowSQL@postgres"
      POSTGRES_DB: flowsql_db
      POSTGRES_USER: flowsql_user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowsql_user -d flowsql_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
