macro(add_subprojets parent)
	file(GLOB dirs LIST_DIRECTORIES true ${parent}/*)
	foreach(dir ${dirs})
		if(IS_DIRECTORY ${dir} AND NOT ${dir} STREQUAL ${CMAKE_BINARY_DIR})
			if(NOT EXISTS ${dir}/CMakeLists.txt)
				add_subprojets(${dir})
			else()
				add_subdirectory(${dir})
			endif()
		endif()
	endforeach()
endmacro()

# 第三方依赖的安装目录，独立于 build 目录，清理重建时不受影响
set(THIRDPARTS_INSTALL_DIR ${CMAKE_SOURCE_DIR}/../.thirdparts_installed)
set(THIRDPARTS_PREFIX_DIR  ${CMAKE_SOURCE_DIR}/../.thirdparts_prefix)

macro(add_thirdparts)
	set(THIRDPARTS_DIR ${CMAKE_SOURCE_DIR}/../thirdparts)
	file(GLOB_RECURSE PROJECTS ${THIRDPARTS_DIR}/*.cmake)
	foreach(PROJECT ${PROJECTS})
		include(${PROJECT})
	endforeach()
endmacro()

macro(add_thirddepen TARGET)
	set(LIBRARIES ${ARGV})
	list(REMOVE_AT LIBRARIES 0)
	foreach(LIBRARY ${LIBRARIES})
		if(TARGET ${LIBRARY})
			add_dependencies(${TARGET} ${LIBRARY})
		endif()
		target_include_directories(${TARGET} PUBLIC ${${LIBRARY}_LINK_INC})
		if(NOT "${${LIBRARY}_LINK_DIR}" STREQUAL "")
			target_link_directories(${TARGET} PUBLIC ${${LIBRARY}_LINK_DIR})
		endif()
		target_link_libraries(${TARGET} -ldl -lpthread ${${LIBRARY}_LINK_TAR})
	endforeach()
endmacro()
